# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.261'
  hooks:
    - id: ruff
      args: [ "--fix", "--exit-non-zero-on-fix" ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: "22.12.0"
  hooks:
  - id: black

- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: 0.2.1
  hooks:
    - id: sync_with_poetry
