# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.4.3'
  hooks:
    - id: ruff
      args: [ "--fix", "--exit-non-zero-on-fix" ]
    - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: 1.1.0
  hooks:
    - id: sync_with_poetry
